apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bom
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/bom.git
    path: kubernetes
    kustomize:
      images:
        - bom=ghcr.io/accurate0/bom:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: bom
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
