apiVersion: apps/v1
kind: Deployment
metadata:
  name: bom
  namespace: bom
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: bom
  replicas: 1
  template:
    metadata:
      labels:
        app: bom
    spec:
      tolerations:
        - key: "group"
          operator: "Equal"
          value: "external"
          effect: "NoSchedule"
      containers:
        - name: bom
          image: bom:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: BUCKET_NAME
              value: bom-images
          envFrom:
            - secretRef:
                name: bom-managed-secrets
            - secretRef:
                name: bom-database-secret
