apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: bom-secret
  namespace: bom
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: bom-bot-f45-b
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: bom-managed-secrets
    secretNamespace: bom
    creationPolicy: "Owner"
